#!/usr/bin/env python3
"""Correct the expected branch count in the monodromy certificate.

psi = -Gamma/Q has a pole of order delta = deg Gamma - deg Q at Y = infinity, so the
point at infinity is itself a ramification point and absorbs delta-1 of the 2n-2 total
ramification. The finite branch values, which are exactly the roots of Delta, therefore
number 2n-2-(delta-1) rather than 2n-2. When delta = 2 that inertia generator is a
transposition like all the others, so the group is transitive and generated by
transpositions, hence S_n.
"""
F = "/tmp/monodromy.cpp"
s = open(F).read()

old_hdr = '''  printf("# %-3s %-6s %-4s %-9s %-9s %-9s %-9s %s\\n",
         "r","n'","d","gcd(Q,G)","Q sqfree","deg Delta","Delta sqfr","verdict");'''
new_hdr = '''  printf("# %-3s %-6s %-4s %-9s %-9s %-4s %-9s %-9s %s\\n",
         "r","n'","d","gcd(Q,G)","Q sqfree","del","deg Delta","Delta sqfr","monodromy");'''
assert old_hdr in s
s = s.replace(old_hdr, new_hdr, 1)

old = '''      long dD = deg(Delta);
      long dsf = (dD>=0) && (deg(GCD(Delta,diff(Delta)))==0);
      bool full = (dg==0) && qsf && (dD==2*np-2) && dsf;
      printf("  %-3ld %-6ld %-4ld %-9ld %-9s %-9ld %-9s %s\\n", r, np, d, dg,
             qsf?"yes":"no", dD, dsf?"yes":"no",
             full ? "monodromy = S_n" : (dg? "reducible pencil (obstructed)" : "certificate fails"));'''
new = '''      long dD = deg(Delta);
      long dsf = (dD>=0) && (deg(GCD(Delta,diff(Delta)))==0);
      long delta = np - deg(Q);
      long expect = 2*np - 2 - (delta - 1);
      bool full = (dg==0) && qsf && dsf && (dD==expect) && (delta==2);
      printf("  %-3ld %-6ld %-4ld %-9ld %-9s %-4ld %-9ld %-9s %s\\n", r, np, d, dg,
             qsf?"yes":"no", delta, dD, dsf?"yes":"no",
             full ? "S_n" : (dg? "reducible (obstructed)"
                               : (dD!=expect ? "branch count off" : "fails")));'''
assert old in s
s = s.replace(old, new, 1)
open(F, "w").write(s)
print("monodromy certificate corrected")
