# sourced by run_batch.sh: maps $MODE -> AUX and HELIB_* flags (uses aux4/aux6 from sets.tsv)
unset HELIB_AUX_ORDER4_EVAL HELIB_COMPOSED_EVAL HELIB_FILTER_ORDER HELIB_EXPLICIT_AUX
case $MODE in
  BASELINE)         AUX=${aux4/-/$aux6} ;;
  ORDER4)           AUX=$aux4; export HELIB_AUX_ORDER4_EVAL=1 ;;
  ORDER4_COMPOSED)  AUX=$aux4; export HELIB_AUX_ORDER4_EVAL=1 HELIB_COMPOSED_EVAL=1 ;;
  ORDER6)           AUX=$aux6; export HELIB_AUX_ORDER4_EVAL=1 HELIB_FILTER_ORDER=6 ;;
  ORDER6_COMPOSED)  AUX=$aux6; export HELIB_AUX_ORDER4_EVAL=1 HELIB_FILTER_ORDER=6 HELIB_COMPOSED_EVAL=1 ;;
  NORMONLY)         AUX=${aux4/-/$aux6}; export HELIB_AUX_ORDER4_EVAL=1 HELIB_FILTER_ORDER=1 HELIB_COMPOSED_EVAL=1 ;;
esac
export HELIB_EXPLICIT_AUX=$AUX
